version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "3000:80"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - db
  server-1:
    image: sampleapp
    environment:
      - APPID=1111  # Note the space after the hyphen
      - PORT=8001
    ports:
      - "8001:8001"
    depends_on:
      - nginx
    networks:
      - db
  server-2:
    image: sampleapp
    environment:
      - APPID=2222  # Note the space after the hyphen
      - PORT=8002
    ports:
      - "8002:8002"
    depends_on:
      - nginx
    networks:
      - db
  server-3:
    image: sampleapp
    environment:
      - APPID=3333  # Note the space after the hyphen
      - PORT=8003
    ports:
      - "8003:8003"
    depends_on:
      - nginx
    networks:
      - db
  server-4:
    image: sampleapp
    environment:
      - APPID=4444  # Note the space after the hyphen
      - PORT=8004
    ports:
      - "8004:8004"
    depends_on:
      - nginx
    networks:
      - db
volumes:
  nginx:
networks:
  db:
    driver: bridge