version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "3000:80"
    volumes:
    - .config/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - db
  log-collector-1:
    image: log-collector
    environment:
      - APPID=1111  # Note the space after the hyphen
      - PORT=8001
    ports:
      - "8001:8001"
    depends_on:
      - nginx
    networks:
      - db
  log-collector-2:
    image: log-collector
    environment:
      - APPID=2222  # Note the space after the hyphen
      - PORT=8002
    ports:
      - "8002:8002"
    depends_on:
      - nginx
    networks:
      - db
volumes:
  nginx:
networks:
  db:
    driver: bridge